const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { generateDailyLog } = require('../../services/taskSummarizer');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('daily')
        .setDescription('Generates a daily work log from Vikunja tasks on a specific date (and caches it in SQLite).')
        .addStringOption(option =>
            option.setName('date')
                .setDescription('The date to generate the log for (e.g., "yesterday", "last friday"). Defaults to today.')
                .setRequired(false)),
    async execute(interaction) {
        await interaction.deferReply();

        try {
            const dateString = interaction.options.getString('date');
            
            // Call the core summarizer service
            const result = await generateDailyLog(dateString);

            if (result.noTasks) {
                return await interaction.editReply(`No relevant completed or in-progress tasks found for ${result.displayDate} in Vikunja.`);
            }

            const embed = new EmbedBuilder()
                .setTitle(`✅ Daily Work Log for ${result.displayDate}${result.cached ? ' (Cached)' : ''}`)
                .setDescription(result.cached ? 'Here is your cached work log:' : 'Here is your AI-generated summary (saved to local database):')
                .addFields({ name: 'Timesheet Log', value: `\`\`\`${result.log}\`\`\`` })
                .setColor(0x00FF00)
                .setFooter({ text: result.cached ? 'Retrieved from local database' : 'Generated by Gemini & cached in SQLite' });

            await interaction.editReply({ embeds: [embed] });

        } catch (error) {
            console.error('Daily Command Error:', error);
            await interaction.editReply({ content: `❌ Error: ${error.message}` });
        }
    },
};
