const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const User = require('../../models/User');
const PlaneService = require('../../services/planeService');
const { createDailyLog, inferDate } = require('../../services/geminiService');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('daily')
        .setDescription('Generates a daily work log from tasks on a specific date.')
        .addStringOption(option =>
            option.setName('date')
                .setDescription('The date to generate the log for (e.g., "yesterday", "last friday"). Defaults to today.')
                .setRequired(false)),
    async execute(interaction) {
        await interaction.deferReply();

        try {
            const user = await User.findOne({ discordId: interaction.user.id });
            if (!user || !user.planeApiKey) {
                return interaction.editReply('You need to link your Plane API key first! Use the `/link` command.');
            }

            const dateString = interaction.options.getString('date');
            let targetDate;
            let displayDate;

            if (dateString) {
                const inferred = await inferDate(dateString);
                if (!inferred) {
                    return interaction.editReply('Could not understand the date. Please try a different format (e.g., "yesterday", "2 days ago", "2023-10-27").');
                }
                targetDate = inferred;
                const [year, month, day] = targetDate.split('-');
                displayDate = `${day}-${month}-${year}`;
            } else {
                const today = new Date();
                targetDate = today.toISOString().split('T')[0];
                const day = String(today.getDate()).padStart(2, '0');
                const month = String(today.getMonth() + 1).padStart(2, '0');
                const year = today.getFullYear();
                displayDate = `${day}-${month}-${year}`;
            }

            const plane = new PlaneService(user.planeApiKey);
            const [tasks, states] = await Promise.all([plane.getTasks(), plane.getStates()]);
            const stateMap = new Map(states.map(s => [s.id, s.name]));

            const relevantTasks = tasks.filter(t => {
                const stateName = stateMap.get(t.state);
                const completedDate = t.completed_at ? new Date(t.completed_at).toISOString().split('T')[0] : null;
                
                const isCompletedOnDate = stateName === 'Done' && completedDate === targetDate;
                const isInProgressOnDate = stateName === 'In Progress' && t.start_date && t.start_date <= targetDate;

                return isCompletedOnDate || isInProgressOnDate;
            });

            if (relevantTasks.length === 0) {
                return await interaction.editReply(`No relevant tasks found for ${displayDate}.`);
            }

            const dailyLog = await createDailyLog(relevantTasks, displayDate);

            const embed = new EmbedBuilder()
                .setTitle(`✅ Daily Work Log for ${displayDate}`)
                .setDescription('Here is your AI-generated summary:')
                .addFields({ name: 'Timesheet Log', value: `\`\`\`${dailyLog}\`\`\`` })
                .setColor(0x00FF00)
                .setFooter({ text: 'Generated by Gemini' });

            await interaction.editReply({ embeds: [embed] });

        } catch (error) {
            console.error('Daily Command Error:', error);
            await interaction.editReply({ content: `❌ Error: ${error.message}` });
        }
    },
};